version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  consumer-blue:
    build: ./consumer
    depends_on:
      - rabbitmq
    restart: on-failure

  consumer-green:
    build: ./consumer
    depends_on:
      - rabbitmq
    restart: on-failure

  producer:
    build: ./producer
    depends_on:
      - rabbitmq
    restart: on-failure
    ports:
      - 8080:8080