version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  consumer-blue:
    build: ./consumer

  consumer-green:
    build: ./consumer

  producer:
    build: ./producer
    ports:
      - 8081:8081